services:
  ai_backend:
    build:
      context: ./ai_backend
    ports:
      - "8000:8000"

  ui_backend:
    build:
      context: ./ui_backend
    ports:
      - "8001:8001"
    depends_on:
      - ai_backend
